#!/usr/bin/env ruby

require 'rubygems'
require 'ruby_gntp'
require 'getopt/declare'

args = Getopt::Declare.new(<<'EOF')

 -t, --title <title>        title for Growl notification   (optional)
 -i, --icon  <url>          icon to use (broken in 1.3+)   (optional)

 message                    (otherwise STDIN is used)      (optional)

EOF

notification = {
  :name   => 'notify',
  :title  => args['-t'] || 'Command-Line Notification',
  :text   => args.unused.empty? ? STDIN.read() : args.unused.join(' '),
}
notification[:icon] = args['-i'] if args['-i'] 

GNTP.notify( notification )

