#!/bin/sh
set -x
set -e

DEV_TOOLS='ant autoconf automake cmake ctags doxygen libtool nasm pkg-config'
REVERSING_TOOLS='radare2'
WEB_TESTING='casperjs phantomjs'
AUDIO_TOOLS='ffmpeg lame'
PRODUCTIVITY_TOOLS='contacts'
SYSADMIN_TOOLS='colordiff coreutils pstree htop-osx watch bwm-ng'
LIBS='bdw-gc gdbm google-perftools nettle libffi libsodium libyaml pcre readline sqlite swig xz'

has() {
  which "$@" >/dev/null 2>&1
}

if ! has ruby; then
  echo 'Must install Xcode Command Line Tools (CLT) first!' >&2
  exit 1
fi
if ! has brew; then # no warts, thanks
  echo 'Installing homebrew'
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew doctor
brew update

uninstall() {
  for ARG in "$@"; do
    case "$@" in
      -*) ;; # skip -...
      *)
      brew unlink "$ARG" || true
      brew uninstall --force "$ARG" || true
    esac
  done
}

reinstall() {
  uninstall "$@"
  brew install "$@"
}

# dev tools
reinstall $DEV_TOOLS

# libs
reinstall $LIBS

# audio tools
reinstall $AUDIO_TOOLS

# sysadmin tools
reinstall $SYSADMIN_TOOLS

# reversing tools
reinstall $REVERSING_TOOLS

reinstall $PRODUCTIVITY_TOOLS

# vim
reinstall vim

# gpg 1.x, cpan and monkeysphere
uninstall gnupg monkeysphere; curl -L https://gist.githubusercontent.com/steakknife/b801b799ea9a8eb801b0/raw/install_monkeysphere.sh | sh

# gpg 2.x
reinstall gnupg2 --8192 --without-libusb-compat --without-dirmngr

# openssl
uninstall openssl; ( export CONFIGURE_OPTS='no-hw no-rdrand no-sctp no-mdc2 no-fips no-zlib no-camellia no-seed no-idea no-exp no-srp no-psk'; \
  brew install https://gist.githubusercontent.com/steakknife/8228264/raw/openssl.rb )

# openssh
uninstall openssh; brew install https://raw.githubusercontent.com/Homebrew/homebrew-dupes/master/openssh.rb --with-keychain-support --with-ldns

# curl and libcurl
reinstall curl --with-rtmp --with-ssh --with-openssl --with-libmetalink --with-gssapi --with-ares

# rsync
uninstall; brew install https://raw.githubusercontent.com/Homebrew/homebrew-dupes/master/rsync.rb

# wget
uninstall wget; brew install https://gist.githubusercontent.com/steakknife/5d7cc206b841d7e2aca0/raw/wget.rb --with-iri --with-pcre

# git
reinstall git --with-brewed-openssl --with-persistent-https --with-pcre --with-brewed-curl --with-blk-sha1

# hg
reinstall mercurial

# svn
reinstall subversion --with-python --ruby --perl

# ruby
reinstall ruby-install --HEAD
reinstall chruby --HEAD

# python
reinstall python

# node
reinstall node

# go
reinstall go

# bash
reinstall bash

# zsh
reinstall zsh

# web testing
# ----------------------
reinstall $WEB_TESTING

# daemons
# -----------------------

# dnscrypt-proxy
reinstall dnscrypt-proxy

# dnsmasq
reinstall dnsmasq --with-dnssec

# nginx
reinstall nginx

# redis
reinstall redis

# postgres
reinstall ossp-uuid
reinstall postgres --with-python
reinstall pg_top

# 0mq
reinstall zmq czmq

# -----------------------

brew cleanup
