#!/bin/sh
set -e

# save bundled gems in vendor/cache
OLD_GEM_HOME="${GEM_HOME}"
export GEM_HOME="`mktemp -d XXXX`"
bundle package # downloads and installs all remote gems for the version of the platform currently running
rm -rf "${GEM_HOME}" # deletes junk gems
GEM_HOME="${OLD_GEM_HOME}"
