#!/bin/sh
set -e

# v--
check_python() {
  python -c 'import ssl;print(ssl.OPENSSL_VERSION)'
}

check_python2() {
  python2 -c 'import ssl;print(ssl.OPENSSL_VERSION)'
}

check_python3() {
  python3 -c 'import ssl;print(ssl.OPENSSL_VERSION)'
}

check_ruby() {
  ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
}

check_node() {
  node -e "console.log(process.versions['openssl']);"
}

check_erlang() {
  erl -connect_all false -noinput -eval 'io:fwrite(element(3,hd(crypto:info_lib()))), io:fwrite("~n").' -run init stop
}

check_system() {
  openssl version
}

check_homebrew() {
  /usr/local/opt/openssl/bin/openssl version
}
# ^--

all() {
  grep -o '^check_[a-z0-9]*' "$0" | sed 's/check_//;/^$/d'
}

check() {
  printf "$1: "
  check_$1
}

if [ -z "$1" ]; then
  all
  exit 1
elif [ "$1" = 'all' ]; then
  for CMD in `all`; do
    check "$CMD"
  done
  exit 0
fi

if all | grep -q "^$1$"; then
  check "$1"
else
  echo "Unknown $1" >&2
  exit 1
fi
