#!/bin/sh
# get my external ip address
# usage: extaddr
curl --proto -all,https,+http \
    --max-filesize 64 \
    --no-buffer \
    --max-time 10 \
    --retry-delay 2 \
    --retry 3 -s -f ifconfig.me \
    | awk '/^([0-9]{1,3}\.){3}[0-9]{1,3}$/&&NR==1'
