#!/bin/sh
#
# If you want to disable auto-imported functions, uncomment the following
# ADD_IMPORT_FUNCTIONS_PATCH=YES install-bash-fix
#
set -e

if [ "$1" = '-u' ]; then
  sudo mv /bin/bash.orig /bin/bash
  sudo mv /bin/sh.orig /bin/sh
  echo 'patched bash uninstalled'
  exit 0
fi

if /bin/bash --version | grep -q '3\.2\.5[1-3]'; then
  echo 'patching bash to 3.2.54'
elif /bin/bash --version | grep -q '3\.2\.54'; then
  echo 'bash already patched to 3.2.54'
  exit 1
else # if bash is too new or too old
  echo 'bash version not patchable'
fi


# prepare
cd $TMPDIR
rm -rf install-bash-fix
mkdir install-bash-fix
cd install-bash-fix

# download
curl https://opensource.apple.com/tarballs/bash/bash-92.tar.gz | tar zxf -

# patch
cd bash-92/bash-3.2
curl https://ftp.gnu.org/pub/gnu/bash/bash-3.2-patches/bash32-052 | patch -p0
curl https://ftp.gnu.org/pub/gnu/bash/bash-3.2-patches/bash32-053 | patch -p0  
if [ "$ADD_IMPORT_FUNCTIONS_PATCH" = YES ]; then
  curl -L https://gist.githubusercontent.com/steakknife/3dc751a485dd069b03eb/raw/import_functions.patch | patch -p0
else
  curl https://ftp.gnu.org/pub/gnu/bash/bash-3.2-patches/bash32-054 | patch -p0
fi
cd ..

# build
xcodebuild

# install
sudo cp -ip /bin/bash /bin/bash.orig
sudo cp -ip /bin/sh /bin/sh.orig
sudo cp -f build/Release/bash /bin/bash
sudo cp -f build/Release/sh /bin/sh

# cleanup
cd ..
rm -rf install-bash-fix
