#!/bin/sh
set -e
help() {
   cat << HELP
usage: $0 ( path/to/file | gist/XXXXXX/file | github/ ){2}
       $0 -d ( path/to/dir | gist/XXXXXX | github){2}
HELP
}

if [ "$1" = '-d' ]; then
  shift
else
  
fi


