#!/bin/sh -ex
#
# Creates a disk image (dmg) on Mac OS X from the command line.
# usage:
#    mkdmg <<srcdir> volname>  
#
# Where <volname> is the name to use for the mounted image, <vers> is the version
# number of the volume and <srcdir> is where the contents to put on the dmg are.
#
# The result will be a file called <volname>.dmg

if [ $# != 2 ]; then
  echo "usage: mkdmg volname srcdir" >&2
  exit 1
fi

DIR="$1"
VOL="$2"

if [ ! -d "$DIR" ]; then
  echo "Folder '$DIR' does not exist" >&2
  exit 1
fi

DMG="$VOL.dmg"
TMPDMG="$VOL.tmp.dmg"

if [ -e "$DMG" ]; then
  echo "DMG '$DMG' already exists!" >&2
  exit 1
fi

# create temporary disk image and format, ejecting when done
SIZE=`du -sk "${DIR-.}" | awk '{print$1}'`
SIZE=$((SIZE*9/8))
hdiutil create -srcfolder "${DIR}" -volname "${VOL}" -fs HFS+ \
	      -fsargs "-c c=64,a=16,e=16" -format UDRW -size ${SIZE}k "${TMPDMG}"

# convert to compressed image, delete temp image
rm -f "$DMG"
hdiutil convert "$TMPDMG" -format UDZO -o "$DMG"
rm -f "$TMPDMG"
