#!/bin/sh

if [ -z "$KEY" ]; then
  echo "Must set wunderground API key using env var KEY" >&2
  exit 1
fi


case "$1" in
c)
    REQUEST_URL="`echo $2 | sed 's/\.html$//'`"
    exec curl "http://api.wunderground.com/api/$KEY/conditions/q/$REQUEST_URL.json"
    ;;
geo)
    LAT="$2"
    LON="$3"
    exec curl "http://api.wunderground.com/api/$KEY/geolookup/q/$LAT,$LON.json"
    ;;
esac

